#!/bin/bash
# by Dominik Stanisław Suchora <suchora.dominik7@gmail.com>
# License: GNU GPLv3

shopt -s extglob

declare maxprocs='1' url _cookies t_pass

IFS=$'\n'

ucurl() {
    curl -k -L -g -m 120 -s -b "$_cookies" --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed "$@" | tr -d '\n\t\r\a\v'
}

get_next_1() {
    reliq '* m@B>".*:.*class=\"navPages\"" [-] | "%i\n"' | recode HTML..UTF8 | sed -E 's#.*<b>[0-9]+</b>##;s#[^<]*<a [^>]*href="([^"]+)".*#\1#;/;all$/d;/^\]/d;/^#/d'
}

get_topic_1() {
    [[ "$1" =~ ^http[s]?://([[:alnum:]-]+\.)+[[:alpha:]]+/.*([?/&;]topic[=,]|-t)([[:digit:]]+) ]] || { echo "improper url - $1"; return; }
    local -r id="${BASH_REMATCH[3]}"
    [ -e "$id" ] && return
    local t="$t_pass"
    t_pass=""
    [ -z "$t" ] && {
        echo "$1" >&2
        t="$(ucurl "$1")"
    }
    local t2 cookies
    local next

    {
    echo "{\"link\":\"$1\",\"id\":$id}"
    reliq '
        .title td #top_subject | "%i" / sed "s/[^:]*: //;s/([^(]*)//;s/&nbsp;//g;s/ *$//",
        .viewed.u td #top_subject | "%i" /  sed "s/.*\(//g;s/.* ([0-9]+) .*/\1/" "E",
        .path.a("\n") div a@[0]; E>(div|span) .nav l@[1]; a .nav | "%i\n" / line [:-1]
    ' <<< "$t"

    while :
    do
        reliq '
            .posts form #quickModForm; table l@[1]; tr l@[1] m@B>"id=\"subject_[0-9]*\""; tr l@[0] m@v>".googlesyndication.com/"; {
                .postid.u div #B>subject_[0-9]* | "%(id)v" / sed "s/.*_//",
                .date td valign=middle; div .smalltext | "%i" / sed "s/.* ://;s/^<\/b> //;s/ &#187;//g;s/<br *\/>.*//;s/<[^>]*>//g;s/ *$//",
                .body div .post | "%i",
                .signature div .signature | "%i",
                .user td valign=top rowspan=2; b l@[1]; a href | "%i",
                .userid.u td valign=top rowspan=2; b l@[1]; a href | "%(href)v" / sed "s/.*;//;s/.*-//;s/\.html$//;s/^u//;s/^=//",
                .avatar td valign=top rowspan=2; img .avatar src | "%(src)v",
                .edited td #B>modified_[0-9]*; * c@[0] | "%i",
                .score span #B>gpbp_score_[0-9]* | "%i",
                .attachments.a("\t") a href #B>link_[0-9]* | "%(href)v\t",
                .userinfo.a("\n") td valign=top rowspan=2; div .smalltext | "%i\n" / sed "s/\(<br \/>\)\+/\n/g" sed "/^$/d;/<img.* class=\"avatar\"/d"
            } |
        ' <<< "$t"

        next="$(get_next_1 <<< "$t")"
        [ -z "$next" ] && break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    } | jq -srcM '.[0] + .[1] + {"posts":(.[2:] | map(.posts[]))}' > "$id"
}

get_forum_1() {
    local t="$t_pass" next
    t_pass=""
    [ -z "$t" ] && {
        echo "$1" >&2
        t="$(ucurl "$1")"
    }
    while :
    do
        for i in $(reliq 'td .windowbg2 m@B>"name=\"b[0-9]*\""; b l@[1]; a href l@[1] | "%(href)v\n"' <<< "$t")
        do
            get_forum_1 "$i"
        done
        for i in $(reliq 'td .B>"windowbg[0-9]*" m@"<span class=\"smalltext\""; a href l@[1] | "%(href)v\n" / sed "s/[.;]msg[^\/]*#new$//;s/#new$//"' <<< "$t")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_topic_1 "$i" &
        done
        next="$(get_next_1 <<< "$t")"
        [ -z "$next" ] && break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    wait
}

get_next_2() {
    reliq 'div .pagelinks [0]; E>(a|span|strong) m@vB>"[a-zA-Z .]" l@[1] | "%(href)v %i\n" / sed "$q; /^ /{N;D;s/ .*//;p;q}" "n"'
}

get_topic_2() {
    local t="$t_pass" id t2 t3 next cookies
    t_pass=""
    [[ "$1" =~ ^http[s]?://([[:alnum:]-]+\.)+[[:alpha:]]+/.*([?/&;]topic[=,])([[:digit:]]+) ]]
    local id="${BASH_REMATCH[3]}"
    [ -z "$id" ] && {
        [ -z "$t" ] && {
            echo "$1" >&2
            t="$(ucurl "$1")"
        }
        id="$(reliq 'input name=sd_topic value | "%(value)v\n"' <<< "$t")"
    }
    [ -e "$id" ] && return
    [ -z "$t" ] && {
        echo "$1" >&2
        t="$(ucurl "$1")"
    }

    {
    echo "{\"link\":\"$1\",\"id\":$id}"

    t2="$(reliq 'div #forumposts; div .cat_bar; h3 .catbg | "%i\n" / sed "s/<[^>]*>//g;s/ &nbsp;/ /;s/ ([^)]*)$//;s/^[^:]*: //"' <<< "$t")"
    if [ -n "$t2" ]
    then
        t3="$(reliq 'div #forumposts; div .cat_bar; h3 .catbg | "%i\n" / sed "s/<[^>]*>//g;s/ &nbsp;/ /;s/.* (\([^)]*\))$/\1/;s/.* \([0-9]*\) .*/\1/"' <<< "$t")"
    else
        t2="$(reliq 'div #forumposts; h1 | "%i\n", B>h[0-9] .display_title; span #top_subject | "%i\n"' <<< "$t")"
        t3="$(reliq 'div #forumposts; div .display-info;  li m@v>"comments" | "%i\n" / sed "s/<[^>]*>//g; s/ .*//"' <<< "$t")"
    fi

    echo '{"title":"'"$t2"'","viewed":"'"$t3"'"}'

    t2="$(reliq '.path.a div .navigate_section [0]; li; a -href=a>action= l@[1]; * c@[0] | "%i\n" / line [:-1]' <<< "$t")"
    [ -z "$t2" ] && t2="$(reliq '.path.a div .container; ol .breadcrumb [0]; li l@[1]; a l@[1]; * c@[0] | "%i\n" / line [:-1]' <<< "$t")"
    echo "$t2"

    while :
    do
        reliq '.posts form #quickModForm; div l@[1]; {
            .postid.u div #B>msg_[0-9]* | "%(id)v" / sed "s/^msg_//",
            .date div .postarea; div .keyinfo; E>(div|a) .smalltext | "%i" / sed "s/.*>//;s/^ //;s/&#187;//;s/ $//",
            .body div .post; div #B>msg_[0-9]* l@[1] | "%i",
            .signature div .signature | "%i",
            .edited * #B>modified_[0-9]* | "%i",
            .attachments.a div .attached; div .attachments_top; a href | "%(href)v\n",
            .user div .poster; h4; a l@[1] | "%i",
            .userid.u div .poster; h4; a href l@[1] | "%(href)v" / sed "s/^.*;u=//",
            .avatar div .poster; { ul #B>msg_[0-9]*_extra_info, ul .user_info }; li .avatar; img src | "%(src)v\n",
            .userinfo div .poster; { ul #B>msg_[0-9]*_extra_info, ul .user_info }; li -.avatar class; {
                .key * l@[0] | "%(class)v",
                .value * l@[0] | "%i"
            } |
        } |' <<< "$t"

        next="$(get_next_2 <<< "$t")"
        [ -z "$next" ] && break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    } | jq -srcM '.[0] + .[1] + .[2] + {"posts":(.[3:] | map(.posts[]))}' > "$id"
}

get_forum_2() {
    local t="$t_pass" next
    t_pass=""
    [ -z "$t" ] && {
        echo "$1" >&2
        t="$(ucurl "$1")"
    }
    while :
    do
        for i in $(reliq '{ * #E>board_[0-9]+, td .windowbg2 }; a E>(name|id)=E>b[0-9]+ href | "%(href)v\n"' <<< "$t")
        do
            get_forum_2 "$i"
        done
        for i in $(reliq 'span #B>msg_[0-9]*; a href | "%(href)v\n"' <<< "$t")
        do
            [ "$(jobs | wc -l)" -gt "$maxprocs" ] && wait %%
            get_topic_2 "$i" &
        done
        next="$(get_next_2 <<< "$t")"
        [ -z "$next" ] && break
        echo "$next" >&2
        t="$(ucurl "$next")"
    done
    wait
}

version_judge() {
    echo "$1" >&2
    t_pass="$(ucurl "$1")"
    if grep -q '>Powered by SMF 1\.[^<]*<' <<< "$t_pass"
    then
        $2 "$1"
    else
        $3 "$1"
    fi
    t_pass=""
}

get_topic() {
    version_judge "$1" 'get_topic_1' 'get_topic_2'
}

get_forum() {
    version_judge "$1" 'get_forum_1' 'get_forum_2'
}

usage() {
    printf '%s [OPTION]... [URL]...\n' "${0##*/}"
    printf 'Scrape smf forums from URL to json.\n\n'
    printf 'Options:\n  -d,\t--dir DIR\t\tchange directory to DIR\n'
    printf '  -p,\t--max-procs NUM\t\tset number of processes to run at a time\n'
    printf '  -b,\t--cookie DATA|FILENAME\tpass cookie to curl\n'
    printf '  -t,\t--topic URL\t\tpass URL as topic link\n'
    printf '     \t--topic1 URL\t\tpass URL as topic link 1.x version\n'
    printf '     \t--topic2 URL\t\tpass URL as topic link 2.x version\n'
    printf '  -f,\t--forum URL\t\tpass URL as forum link\n'
    printf '     \t--forum1 URL\t\tpass URL as forum link 1.x version\n'
    printf '     \t--forum2 URL\t\tpass URL as forum link 2.x version\n'
    printf '  -h,\t--help\t\t\tshow this message\n'
}

[ "$#" -eq 0 ] && { usage >&2; exit 1; }

while [ "$#" -gt 0 ]
do
    case "$1" in
        -d|--dir) cd "$2" || break; shift;;
        -t|--topic)
            get_topic "$2"
            shift;;
        --topic1)
            get_topic_1 "$2"
            shift;;
        --topic2)
            get_topic_2 "$2"
            shift;;
        -f|--forum)
            get_forum "$2"
            shift;;
        --forum1)
            get_forum_1 "$2"
            shift;;
        --forum2)
            get_forum_2 "$2"
            shift;;
        -b|--cookie) _cookies="$2"; shift;;
        -p|--max-procs) maxprocs="$2"; shift;;
        -h|--help) usage >&2; exit;;
        -*) usage >&2; exit 1;;
        *) break;;
    esac
    shift
done

while [ "$#" -gt 0 ]
do
    case "$1" in
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])/*@([?/&;]topic[=,]|-t)+([[:digit:]])*)
            get_topic "$1";;
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])/*@([?/&;]board[=,]|-t)+([[:digit:]])*)
            get_forum "$1";;
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])/?(*/)index.php*)
            get_forum "$1";;
        http?(s)://+(+([[:alnum:]-]).)+([[:alpha:]])*)
            get_forum "$1";
    esac
    shift
done
